AspCoreMvc_App/Models/UserData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspCoreMvc_App.Models
{
    public class UserData
    {
        [Display(Name = "User Name")]
        [Required(ErrorMessage = "Please input username!")]
        public string Username { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please input password!")]
        public string Password { get; set; }

        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Does not match!")]
        public string ConfirmPassword { get; set; }


    }
}

AspCoreMvc_App/Controllers/UserDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspCoreMvc_App.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using App.Library;

namespace AspCoreMvc_App.Controllers
{
    public class UserDataController : Controller
    {

        private readonly StudentDetailContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public UserDataController(StudentDetailContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }


        [AllowAnonymous]
        public IActionResult Index()
        {
            if (!HttpContext.Request.Cookies.ContainsKey(".AspNetCore.Identity.Application"))
            {
                ViewBag.ReturnUrl = HttpContext.Request.Query["ReturnUrl"].ToString();

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }            
        }

        [AllowAnonymous]
        [HttpPost]
        //string uname, string pwd
        public async Task<IActionResult> Verify(SignedUser p)
        {
            string returnUrl = HttpContext.Request.Query["ReturnUrl"].ToString();

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(p.Username, p.Password, false, true);
                if (result.Succeeded)
                {
                    //if (redirectUrl != "" && redirectCtrl != "")
                    if(returnUrl != "")
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        //Just redirect to our index after logging in. 
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return View("Index");
        }


        [AllowAnonymous]
        [HttpPost]
        [Route("[controller]/[action]")]
        //string name, string pw, string cnf_pw
        public async Task<IActionResult> CreateAsync(UserData p)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser()
                {
                    UserName = p.Username
                };
                var result = await _userManager.CreateAsync(user, p.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View("Index");

        }

        public async Task<IActionResult> Log_Out()
        {

            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

AspCoreMvc_App/Views/UserData/Create.cshtml
@model string

<div>Created @Model</div>

AspCoreMvc_App/Views/UserData/Index.cshtml
@*@model UserData*@
@model Tuple<UserData, SignedUser>
@{
    ViewData["Title"] = "Log-in";
    Layout = null;
}
<style>
    import url(https://fonts.googleapis.com/css?family=Roboto:300);

    .login-page {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #4CAF50;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

            .form button:hover, .form button:active, .form button:focus {
                background: #43A047;
            }

        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }

            .form .message a {
                color: #4CAF50;
                text-decoration: none;
            }

        .form .register-form {
            display: none;
        }

    .container {
        position: relative;
        z-index: 1;
        max-width: 300px;
        margin: 0 auto;
    }

        .container:before, .container:after {
            content: "";
            display: block;
            clear: both;
        }

        .container .info {
            margin: 50px auto;
            text-align: center;
        }

            .container .info h1 {
                margin: 0 0 15px;
                padding: 0;
                font-size: 36px;
                font-weight: 300;
                color: #1a1a1a;
            }

            .container .info span {
                color: #4d4d4d;
                font-size: 12px;
            }

                .container .info span a {
                    color: #000000;
                    text-decoration: none;
                }

                .container .info span .fa {
                    color: #EF3B3A;
                }

    body {
        background: #76b852; /* fallback for old browsers */
        background: rgb(141,194,111);
        background: linear-gradient(90deg, rgba(141,194,111,1) 0%, rgba(118,184,82,1) 50%);
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('.message a').click(function () {
            $('form').animate({ height: "toggle", opacity: "toggle" }, "slow");
        });
    });
</script>

<div class="login-page" style="margin-top: 10%">
    <div class="form">
        <form asp-controller="UserData" asp-action="Create" class="register-form" method="post">
            <div class="form-group">
                <span asp-validation-for="@Model.Item1.Username" class="text-danger"></span>
                <input name="Username" type="text" asp-for="@Model.Item1.Username" placeholder="Username" />
            </div>
            <div class="form-group">
                <span asp-validation-for="@Model.Item1.Password" class="text-danger"></span>
                <input name="Password" type="password" asp-for="@Model.Item1.Password" placeholder="Password" />
            </div>
            <div class="form-group">
                <span asp-validation-for="@Model.Item1.ConfirmPassword" class="text-danger"></span>
                <input name="ConfirmPassword" type="password" asp-for="@Model.Item1.ConfirmPassword" placeholder="Confirm password" />
            </div>
            <button>create</button>
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>
        @*asp-route-redirectUrl=@ViewBag.redirectUrl asp-route-redirectCtrl=@ViewBag.redirectCtrl*@
        <form asp-controller="UserData" asp-action="Verify" asp-route-ReturnUrl="@ViewBag.ReturnUrl" class="login-form" method="post">
            <input name="Username" type="text" asp-for="@Model.Item2.Username" placeholder="username" />
            <input name="Password" type="password" asp-for="@Model.Item2.Password" placeholder="password" />
            <button>login</button>
            <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>
    </div>
</div>

AspCoreMvc_App/Views/UserData/Verify.cshtml
@model string

<div>
    Logged in @Model
</div>